"""Seed exercise database for Athos.
Categories: barbell, dumbbell, machine, cable, smith, bodyweight, cardio

Design notes:
- Broad equipment coverage: cable / smith / dumbbell / barbell / machine
  variants wherever the movement makes physical sense.
- No "single-arm" / "single-side" entries — the workout logger has an L/R
  (unilateral) toggle, so users add single-arm work to any exercise at log time.
- is_unilateral defaults to False for everything; the toggle handles it.
"""

SEED_EXERCISES = [
    # ===================== CHEST =====================
    {"name": "Barbell Bench Press", "category": "barbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Incline Barbell Bench Press", "category": "barbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Decline Barbell Bench Press", "category": "barbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Wide-Grip Bench Press", "category": "barbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Barbell Floor Press", "category": "barbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Pin Press", "category": "barbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Dumbbell Bench Press", "category": "dumbbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Incline Dumbbell Bench Press", "category": "dumbbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Decline Dumbbell Bench Press", "category": "dumbbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Dumbbell Fly", "category": "dumbbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Incline Dumbbell Fly", "category": "dumbbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Dumbbell Pullover", "category": "dumbbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Svend Press", "category": "dumbbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Smith Machine Bench Press", "category": "smith", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Incline Smith Machine Bench Press", "category": "smith", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Decline Smith Machine Bench Press", "category": "smith", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Chest Press Machine", "category": "machine", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Incline Chest Press Machine", "category": "machine", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Decline Chest Press Machine", "category": "machine", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Pec Deck Machine", "category": "machine", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Pec Fly Machine", "category": "machine", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Cable Chest Fly", "category": "cable", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Cable Crossover", "category": "cable", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Low Cable Fly", "category": "cable", "muscle_group": "chest", "is_unilateral": False},
    {"name": "High Cable Fly", "category": "cable", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Cable Bench Press", "category": "cable", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Cable Incline Press", "category": "cable", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Seated Cable Pec Fly", "category": "cable", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Standing Cable Pec Fly", "category": "cable", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Landmine Press", "category": "barbell", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Push-Up", "category": "bodyweight", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Incline Push-Up", "category": "bodyweight", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Decline Push-Up", "category": "bodyweight", "muscle_group": "chest", "is_unilateral": False},
    {"name": "Chest Dip", "category": "bodyweight", "muscle_group": "chest", "is_unilateral": False},

    # ===================== BACK =====================
    {"name": "Barbell Deadlift", "category": "barbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Sumo Deadlift", "category": "barbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Deficit Deadlift", "category": "barbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Rack Pull", "category": "barbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Trap Bar Deadlift", "category": "barbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Barbell Bent-Over Row", "category": "barbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Pendlay Row", "category": "barbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Yates Row", "category": "barbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Landmine Row", "category": "barbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Meadows Row", "category": "barbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Seal Row", "category": "barbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Dumbbell Row", "category": "dumbbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Chest-Supported Dumbbell Row", "category": "dumbbell", "muscle_group": "back", "is_unilateral": False},
    {"name": "Smith Machine Row", "category": "smith", "muscle_group": "back", "is_unilateral": False},
    {"name": "Smith Machine Deadlift", "category": "smith", "muscle_group": "back", "is_unilateral": False},
    {"name": "Lat Pulldown", "category": "cable", "muscle_group": "back", "is_unilateral": False},
    {"name": "Wide-Grip Lat Pulldown", "category": "cable", "muscle_group": "back", "is_unilateral": False},
    {"name": "Close-Grip Lat Pulldown", "category": "cable", "muscle_group": "back", "is_unilateral": False},
    {"name": "Neutral-Grip Lat Pulldown", "category": "cable", "muscle_group": "back", "is_unilateral": False},
    {"name": "Straight-Arm Pulldown", "category": "cable", "muscle_group": "back", "is_unilateral": False},
    {"name": "Seated Cable Row", "category": "cable", "muscle_group": "back", "is_unilateral": False},
    {"name": "Cable Pullover", "category": "cable", "muscle_group": "back", "is_unilateral": False},
    {"name": "Lat Pulldown Machine", "category": "machine", "muscle_group": "back", "is_unilateral": False},
    {"name": "Seated Row Machine", "category": "machine", "muscle_group": "back", "is_unilateral": False},
    {"name": "T-Bar Row Machine", "category": "machine", "muscle_group": "back", "is_unilateral": False},
    {"name": "Hammer Strength Row", "category": "machine", "muscle_group": "back", "is_unilateral": False},
    {"name": "Chest-Supported Machine Row", "category": "machine", "muscle_group": "back", "is_unilateral": False},
    {"name": "Assisted Pull-Up Machine", "category": "machine", "muscle_group": "back", "is_unilateral": False},
    {"name": "Back Extension Machine", "category": "machine", "muscle_group": "back", "is_unilateral": False},
    {"name": "Pull-Up", "category": "bodyweight", "muscle_group": "back", "is_unilateral": False},
    {"name": "Wide-Grip Pull-Up", "category": "bodyweight", "muscle_group": "back", "is_unilateral": False},
    {"name": "Neutral-Grip Pull-Up", "category": "bodyweight", "muscle_group": "back", "is_unilateral": False},
    {"name": "Chin-Up", "category": "bodyweight", "muscle_group": "back", "is_unilateral": False},
    {"name": "Inverted Row", "category": "bodyweight", "muscle_group": "back", "is_unilateral": False},
    {"name": "Back Extension", "category": "bodyweight", "muscle_group": "back", "is_unilateral": False},

    # ===================== SHOULDERS =====================
    {"name": "Barbell Overhead Press", "category": "barbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Barbell Push Press", "category": "barbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Behind-the-Neck Press", "category": "barbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Z-Press", "category": "barbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Barbell Upright Row", "category": "barbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Barbell Front Raise", "category": "barbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Dumbbell Shoulder Press", "category": "dumbbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Seated Dumbbell Press", "category": "dumbbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Arnold Press", "category": "dumbbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Dumbbell Lateral Raise", "category": "dumbbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Dumbbell Front Raise", "category": "dumbbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Dumbbell Rear Delt Fly", "category": "dumbbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Dumbbell Upright Row", "category": "dumbbell", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Smith Machine Shoulder Press", "category": "smith", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Smith Machine Upright Row", "category": "smith", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Shoulder Press Machine", "category": "machine", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Lateral Raise Machine", "category": "machine", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Rear Delt Machine", "category": "machine", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Reverse Pec Deck", "category": "machine", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Cable Lateral Raise", "category": "cable", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Cable Front Raise", "category": "cable", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Cable Rear Delt Fly", "category": "cable", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Cable Upright Row", "category": "cable", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Cable Y-Raise", "category": "cable", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Face Pull", "category": "cable", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Pike Push-Up", "category": "bodyweight", "muscle_group": "shoulders", "is_unilateral": False},
    {"name": "Handstand Push-Up", "category": "bodyweight", "muscle_group": "shoulders", "is_unilateral": False},

    # ===================== BICEPS =====================
    {"name": "Barbell Bicep Curl", "category": "barbell", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "EZ-Bar Curl", "category": "barbell", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Barbell Preacher Curl", "category": "barbell", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Reverse Curl", "category": "barbell", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Drag Curl", "category": "barbell", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Dumbbell Bicep Curl", "category": "dumbbell", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Hammer Curl", "category": "dumbbell", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Incline Dumbbell Curl", "category": "dumbbell", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Spider Curl", "category": "dumbbell", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Zottman Curl", "category": "dumbbell", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Cable Bicep Curl", "category": "cable", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Cable Hammer Curl", "category": "cable", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Cable Preacher Curl", "category": "cable", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Bayesian Cable Curl", "category": "cable", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Preacher Curl Machine", "category": "machine", "muscle_group": "biceps", "is_unilateral": False},
    {"name": "Bicep Curl Machine", "category": "machine", "muscle_group": "biceps", "is_unilateral": False},

    # ===================== TRICEPS =====================
    {"name": "Close-Grip Bench Press", "category": "barbell", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Barbell Skullcrusher", "category": "barbell", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "EZ-Bar Skullcrusher", "category": "barbell", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "JM Press", "category": "barbell", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Dumbbell Tricep Extension", "category": "dumbbell", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Overhead Dumbbell Tricep Extension", "category": "dumbbell", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Dumbbell Tricep Kickback", "category": "dumbbell", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Dumbbell Skullcrusher", "category": "dumbbell", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Smith Machine Close-Grip Bench Press", "category": "smith", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Cable Tricep Extension", "category": "cable", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Tricep Pushdown", "category": "cable", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Cable Rope Pushdown", "category": "cable", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Straight-Bar Pushdown", "category": "cable", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "V-Bar Pushdown", "category": "cable", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Overhead Cable Tricep Extension", "category": "cable", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Rope Overhead Tricep Extension", "category": "cable", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Cable Tricep Kickback", "category": "cable", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Tricep Extension Machine", "category": "machine", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Tricep Dip Machine", "category": "machine", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Dip", "category": "bodyweight", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Bench Dip", "category": "bodyweight", "muscle_group": "triceps", "is_unilateral": False},
    {"name": "Diamond Push-Up", "category": "bodyweight", "muscle_group": "triceps", "is_unilateral": False},

    # ===================== LEGS: QUADS / SQUAT =====================
    {"name": "Barbell Back Squat", "category": "barbell", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Barbell Front Squat", "category": "barbell", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Barbell Box Squat", "category": "barbell", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Pause Squat", "category": "barbell", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Barbell Lunge", "category": "barbell", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Dumbbell Goblet Squat", "category": "dumbbell", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Dumbbell Squat", "category": "dumbbell", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Bulgarian Split Squat", "category": "dumbbell", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Dumbbell Lunge", "category": "dumbbell", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Dumbbell Walking Lunge", "category": "dumbbell", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Dumbbell Reverse Lunge", "category": "dumbbell", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Dumbbell Step-Up", "category": "dumbbell", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Smith Machine Squat", "category": "smith", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Smith Machine Front Squat", "category": "smith", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Smith Machine Lunge", "category": "smith", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Smith Machine Bulgarian Split Squat", "category": "smith", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Leg Press Machine", "category": "machine", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Hack Squat Machine", "category": "machine", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Reverse Hack Squat", "category": "machine", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Belt Squat", "category": "machine", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Leg Extension Machine", "category": "machine", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Sissy Squat", "category": "bodyweight", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Air Squat", "category": "bodyweight", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Jump Squat", "category": "bodyweight", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Pistol Squat", "category": "bodyweight", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Bodyweight Lunge", "category": "bodyweight", "muscle_group": "quads", "is_unilateral": False},
    {"name": "Reverse Lunge", "category": "bodyweight", "muscle_group": "quads", "is_unilateral": False},

    # ===================== LEGS: HAMSTRINGS / GLUTES =====================
    {"name": "Romanian Deadlift", "category": "barbell", "muscle_group": "hamstrings", "is_unilateral": False},
    {"name": "Barbell Good Morning", "category": "barbell", "muscle_group": "hamstrings", "is_unilateral": False},
    {"name": "Dumbbell Romanian Deadlift", "category": "dumbbell", "muscle_group": "hamstrings", "is_unilateral": False},
    {"name": "Smith Machine Romanian Deadlift", "category": "smith", "muscle_group": "hamstrings", "is_unilateral": False},
    {"name": "Leg Curl Machine", "category": "machine", "muscle_group": "hamstrings", "is_unilateral": False},
    {"name": "Seated Leg Curl Machine", "category": "machine", "muscle_group": "hamstrings", "is_unilateral": False},
    {"name": "Lying Leg Curl Machine", "category": "machine", "muscle_group": "hamstrings", "is_unilateral": False},
    {"name": "Nordic Hamstring Curl", "category": "bodyweight", "muscle_group": "hamstrings", "is_unilateral": False},
    {"name": "Glute Ham Raise", "category": "bodyweight", "muscle_group": "hamstrings", "is_unilateral": False},
    {"name": "Barbell Hip Thrust", "category": "barbell", "muscle_group": "glutes", "is_unilateral": False},
    {"name": "Barbell Glute Bridge", "category": "barbell", "muscle_group": "glutes", "is_unilateral": False},
    {"name": "Smith Machine Hip Thrust", "category": "smith", "muscle_group": "glutes", "is_unilateral": False},
    {"name": "Hip Thrust Machine", "category": "machine", "muscle_group": "glutes", "is_unilateral": False},
    {"name": "Glute Kickback Machine", "category": "machine", "muscle_group": "glutes", "is_unilateral": False},
    {"name": "Hip Abduction Machine", "category": "machine", "muscle_group": "glutes", "is_unilateral": False},
    {"name": "Hip Adduction Machine", "category": "machine", "muscle_group": "legs", "is_unilateral": False},
    {"name": "Cable Pull-Through", "category": "cable", "muscle_group": "glutes", "is_unilateral": False},
    {"name": "Cable Glute Kickback", "category": "cable", "muscle_group": "glutes", "is_unilateral": False},
    {"name": "Cable Hip Abduction", "category": "cable", "muscle_group": "glutes", "is_unilateral": False},
    {"name": "Glute Bridge", "category": "bodyweight", "muscle_group": "glutes", "is_unilateral": False},
    {"name": "Hip Thrust (Bodyweight)", "category": "bodyweight", "muscle_group": "glutes", "is_unilateral": False},

    # ===================== CALVES =====================
    {"name": "Standing Calf Raise Machine", "category": "machine", "muscle_group": "calves", "is_unilateral": False},
    {"name": "Seated Calf Raise Machine", "category": "machine", "muscle_group": "calves", "is_unilateral": False},
    {"name": "Leg Press Calf Raise", "category": "machine", "muscle_group": "calves", "is_unilateral": False},
    {"name": "Smith Machine Calf Raise", "category": "smith", "muscle_group": "calves", "is_unilateral": False},
    {"name": "Barbell Calf Raise", "category": "barbell", "muscle_group": "calves", "is_unilateral": False},
    {"name": "Dumbbell Calf Raise", "category": "dumbbell", "muscle_group": "calves", "is_unilateral": False},
    {"name": "Calf Raise (Bodyweight)", "category": "bodyweight", "muscle_group": "calves", "is_unilateral": False},

    # ===================== TRAPS / FOREARMS =====================
    {"name": "Barbell Shrug", "category": "barbell", "muscle_group": "traps", "is_unilateral": False},
    {"name": "Dumbbell Shrug", "category": "dumbbell", "muscle_group": "traps", "is_unilateral": False},
    {"name": "Smith Machine Shrug", "category": "smith", "muscle_group": "traps", "is_unilateral": False},
    {"name": "Cable Shrug", "category": "cable", "muscle_group": "traps", "is_unilateral": False},
    {"name": "Trap Bar Shrug", "category": "barbell", "muscle_group": "traps", "is_unilateral": False},
    {"name": "Wrist Curl", "category": "dumbbell", "muscle_group": "forearms", "is_unilateral": False},
    {"name": "Reverse Wrist Curl", "category": "dumbbell", "muscle_group": "forearms", "is_unilateral": False},
    {"name": "Barbell Wrist Curl", "category": "barbell", "muscle_group": "forearms", "is_unilateral": False},
    {"name": "Cable Wrist Curl", "category": "cable", "muscle_group": "forearms", "is_unilateral": False},
    {"name": "Farmer's Carry", "category": "dumbbell", "muscle_group": "forearms", "is_unilateral": False},

    # ===================== CORE =====================
    {"name": "Cable Crunch", "category": "cable", "muscle_group": "core", "is_unilateral": False},
    {"name": "Cable Woodchopper", "category": "cable", "muscle_group": "core", "is_unilateral": False},
    {"name": "Pallof Press", "category": "cable", "muscle_group": "core", "is_unilateral": False},
    {"name": "Ab Crunch Machine", "category": "machine", "muscle_group": "core", "is_unilateral": False},
    {"name": "Ab Wheel Rollout", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Plank", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Side Plank", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Crunch", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Sit-Up", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Decline Sit-Up", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Russian Twist", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Bicycle Crunch", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Leg Raise", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Hanging Leg Raise", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Hanging Knee Raise", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Toes-to-Bar", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Dead Bug", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},
    {"name": "Mountain Climber", "category": "bodyweight", "muscle_group": "core", "is_unilateral": False},

    # ===================== FULL BODY / OLYMPIC =====================
    {"name": "Power Clean", "category": "barbell", "muscle_group": "full_body", "is_unilateral": False},
    {"name": "Hang Clean", "category": "barbell", "muscle_group": "full_body", "is_unilateral": False},
    {"name": "Clean and Jerk", "category": "barbell", "muscle_group": "full_body", "is_unilateral": False},
    {"name": "Snatch", "category": "barbell", "muscle_group": "full_body", "is_unilateral": False},
    {"name": "Thruster", "category": "barbell", "muscle_group": "full_body", "is_unilateral": False},
    {"name": "Muscle-Up", "category": "bodyweight", "muscle_group": "full_body", "is_unilateral": False},
    {"name": "Burpee", "category": "bodyweight", "muscle_group": "full_body", "is_unilateral": False},
    {"name": "Box Jump", "category": "bodyweight", "muscle_group": "full_body", "is_unilateral": False},

    # ===================== CARDIO =====================
    {"name": "Running", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Treadmill Run", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Outdoor Run", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Sprint Intervals", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Cycling", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Stationary Bike", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Assault Bike", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Rowing Machine", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Elliptical", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Stair Climber", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Jump Rope", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Swimming", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Walking", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Hiking", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Battle Ropes", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Sled Push", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
    {"name": "Sled Pull", "category": "cardio", "muscle_group": "cardio", "is_unilateral": False},
]

# Default machine variants per machine exercise (for "Machine Selection" feature)
DEFAULT_MACHINES = [
    "Hammer Strength",
    "Life Fitness",
    "Cybex",
    "Technogym",
    "Nautilus",
    "Planet Fitness",
    "Generic Machine",
]
